<div id="ps_notice" style="display: block;" class="payment_redirect_message">
    {'Redirecting to %s payment system'|t:'PayU'}.
</div>

  <form accept-charset="UTF-8" action="{$form_url}" method="post" id="ps_form">
  <input name="merchantId"    type="hidden"  value={$merchant_id}   >
  <input name="accountId"     type="hidden"  value="{account_id}" >
  <input name="description"   type="hidden"  value="{$description}"  >
  <input name="referenceCode" type="hidden"  value="${reference_code}" >
  <input name="amount"        type="hidden"  value="${amount}"   >
  <input name="tax"           type="hidden"  value="0"  >
  <input name="taxReturnBase" type="hidden"  value="0" >
  <input name="currency"      type="hidden"  value="${currency}" >
  <input name="signature"     type="hidden"  value="${signature}">
  <input name="test"          type="hidden"  value="0" >
  <input name="buyerFullName" type="hidden"  value="${buyer_fullname}" >
  <input name="buyerEmail"    type="hidden"  value="${buyer_email}" >
  <input name="responseUrl"    type="hidden"  value="${response_url}" >
  <input name="confirmationUrl"    type="hidden"  value="${confirmation_url}" >
  <input type="submit" value="{'Paga Ahora'|t}" id="pay_btn" />

</form>


{literal}
<script type="text/javascript">
  document.getElementById("pay_btn").style.display = "none";
  document.getElementById("ps_notice").style.display = "block";

  window.onload = function() {
      document.getElementById("ps_form").submit();
  }
</script>
{/literal}

